services:
  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    networks:
      - adguard-network
    ports:
      - 3000:3000/tcp
      - 53:53/tcp
      - 53:53/udp
      - 67:67/tcp
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      - 8082:80/tcp
    restart: "unless-stopped"
    volumes:
      - "${APP_DATA}/AdGuardHome/config:/opt/adguardhome/conf"
      - "${APP_DATA}/AdGuardHome/work:/opt/adguardhome/work"

networks:
  adguard-network:
